//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web06.APIS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web06.APIS.Core.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string VN_Email {
            get {
                return ResourceManager.GetString("VN_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sai định dạng.
        /// </summary>
        public static string VN_EmailInvalid {
            get {
                return ResourceManager.GetString("VN_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập thông tin người dùng.
        /// </summary>
        public static string VN_ErrorOfInvalidUser {
            get {
                return ResourceManager.GetString("VN_ErrorOfInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string VN_FullName {
            get {
                return ResourceManager.GetString("VN_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được để trống.
        /// </summary>
        public static string VN_FullNameEmpty {
            get {
                return ResourceManager.GetString("VN_FullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string VN_Index {
            get {
                return ResourceManager.GetString("VN_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng không hợp lệ.xlsx.
        /// </summary>
        public static string VN_InvalidUsersExcelFile {
            get {
                return ResourceManager.GetString("VN_InvalidUsersExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NGƯỜI DÙNG KHÔNG HỢP LỆ.
        /// </summary>
        public static string VN_InvalidUsersExcelWorkSheet {
            get {
                return ResourceManager.GetString("VN_InvalidUsersExcelWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string VN_JobTitle {
            get {
                return ResourceManager.GetString("VN_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không được để trống.
        /// </summary>
        public static string VN_JobTitleEmpty {
            get {
                return ResourceManager.GetString("VN_JobTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại cá nhân.
        /// </summary>
        public static string VN_Mobile {
            get {
                return ResourceManager.GetString("VN_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string VN_Organization {
            get {
                return ResourceManager.GetString("VN_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống.
        /// </summary>
        public static string VN_OrganizationEmpty {
            get {
                return ResourceManager.GetString("VN_OrganizationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string VN_OrganizationUnit {
            get {
                return ResourceManager.GetString("VN_OrganizationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được để trống.
        /// </summary>
        public static string VN_OrganizationUnitEmpty {
            get {
                return ResourceManager.GetString("VN_OrganizationUnitEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại sai định dạng.
        /// </summary>
        public static string VN_PhoneInvalid {
            get {
                return ResourceManager.GetString("VN_PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string VN_Status {
            get {
                return ResourceManager.GetString("VN_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string VN_Status_Active {
            get {
                return ResourceManager.GetString("VN_Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string VN_Status_Inactive {
            get {
                return ResourceManager.GetString("VN_Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        public static string VN_UserGroup {
            get {
                return ResourceManager.GetString("VN_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng.xlsx.
        /// </summary>
        public static string VN_UsersExcelFile {
            get {
                return ResourceManager.GetString("VN_UsersExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách người dùng (bản mẫu).xlsx.
        /// </summary>
        public static string VN_UsersExcelFileTemplate {
            get {
                return ResourceManager.GetString("VN_UsersExcelFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NGƯỜI DÙNG .
        /// </summary>
        public static string VN_UsersExcelWorkSheet {
            get {
                return ResourceManager.GetString("VN_UsersExcelWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại cơ quan.
        /// </summary>
        public static string VN_WorkPhone {
            get {
                return ResourceManager.GetString("VN_WorkPhone", resourceCulture);
            }
        }
    }
}
